### PR TITLE
(Feature) Transfer tokens

### PR DESCRIPTION
**Pull request by vbaranov**
Relates to https://github.com/poanetwork/metamask-extension/issues/134
Built on  https://github.com/poanetwork/metamask-extension/pull/142 (should be merged after this PR)

The last part of tokens' management support; the ability to transfer tokens.

@dennis00010011b e2e tests are affected with this feature, could you please update e2e tests to support this feature also?

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@vbaranov 
Send tokens dialog: 
 1. No decimals validation. There is should be any error message like ' ... decimals should not exceed the amount of decimals specified... ' if fractional part of amount  longer than specified of decimals

 2. Can not send valid amount of token with more than 16 significant digits (even if token decimals =18), button 'Next ' is non-clickable, uncaught error in console 

screen shot 2018-09-27 at 6 15 01 am

**Comment by vbaranov** [comment]
@dennis00010011b 

>No decimals validation. There is should be any error message like ' ... decimals should not exceed the amount of decimals specified... ' if fractional part of amount longer than specified of decimals

Could you please create an additional issue for that? For now, all extra decimals should be truncated on the confirmation page before sending transaction.

>Can not send valid amount of token with more than 16 significant digits (even if token decimals =18), button 'Next ' is non-clickable, uncaught error in console

Should work now (bignumber errors were disabled for this page)

**Comment by dennis00010011b** [comment]
@vbaranov 
Send tokens: error message typo 
Should be '.. token's ..'
screen shot 2018-09-27 at 9 12 41 am

**Comment by vbaranov** [comment]
>I can fix it in e2e PR

@dennis00010011b thank you

**Comment by dennis00010011b** [comment]
@vbaranov 
Firefox, Send tokens screen: 
 -field address has no arrow icon
 -there is no hex addresses in dropdown list 

screen shot 2018-09-28 at 4 08 59 am

**Comment by dennis00010011b** [comment]
@vbaranov 
https://github.com/poanetwork/metamask-extension/blob/a297e0d9dd690d93a7af1cd4f9251207e14c84ac/old-ui/app/send-token.js#L324

Should be `const parts = input.split('.') ` ?

**Comment by dennis00010011b** [comment]
@vbaranov 
Firefox-Send tokens: no error message if amount too precise, clicking button 'Next' leads to open 'Confirm transaction' dialog

It  works in Chrome:

screen shot 2018-09-28 at 6 09 04 am

**Comment by vbaranov** [comment]
@dennis00010011b 

>Should be const parts = input.split('.') ?

Right, nice catch!

Could you create additional issues for FF bugs with the label `FF related`?

**Pull request merged**
