### PR TITLE
(Feature) Support POA network

### LINKED ISSUE #2: Support POA network
**Goals:**
- [ ] Make POA default network
- [ ]  Open txs in [poaexplorer](poaexplorer.com)

**References:**
- [Previous fork repository](https://github.com/oraclesorg/metamask-plugin)
- Relevant commits:
  - [1572538](1572538b269ff678069cbed9a6b70658db5adeaf)
  - [1e9ddef](1e9ddef9c4f88eef47aa395bdafffe04fcb0d745)
  - [6f6cca9](6f6cca99758772795f2e8dafa3c53fa82aa4bbbc)
- [Sparrow browser extension for Ubiq](https://github.com/ubiq/sparrow-extension)

### PR DESCRIPTION
**Pull request by fvictorio**
Closes #2.

This PR:
- Adds support for POA Network
- Uses it by default (when installing the extension, not when using unpacked)
- Make it the first item in the list
- Uses the POA explorer for showing accounts and transactions
- Uses `POA` as symbol instead of `ETH`

### CODE REVIEW

**Comment by fvictorio** [comment]
@vbaranov Sure.

**Comment by vbaranov** [comment]
@fvictorio and also, let's change "BUY ETH" to "BUY POA" in case of POA

**Comment by fvictorio** [comment]
> @fvictorio and also, let's change "BUY ETH" to "BUY POA" in case of POA

Done.

**Comment by vbaranov** [comment]
@fvictorio I still see the button name "POA NETWORK TEST FAUCET" for core network

**Comment by fvictorio** [comment]
Oh, sorry, I changed the "BUY ETH" title to "BUY POA", not the button. I'll change that too.

**Comment by fvictorio** [comment]
@vbaranov Done.

**Pull request merged**
