### PR TITLE
(Upgrade) get upstream from MM 4.11.0

### PR DESCRIPTION
**Pull request by vbaranov**
get upstream from MM 4.11.0

### CODE REVIEW

**Comment by vbaranov** [comment]
@dennis00010011b, please update unit, integration and e2e tests. Please let me know if any component is broken.

**Comment by dennis00010011b** [comment]
@vbaranov 
Add token in Main network: original icon isn't displayed

screen shot 2018-10-25 at 2 22 55 pm

**Comment by dennis00010011b** [comment]
@vbaranov 
Unit tests were failed because function `addToken` in `preference controller`  has additional parameter `image`
https://github.com/poanetwork/metamask-extension/blob/36c8c15ecb211e11e3aaf1568b1fe9db07f79970/app/scripts/controllers/preferences.js#L312

**Comment by vbaranov** [comment]
>Add token in Main network: original icon isn't displayed

@dennis00010011b good catch! Thanks. Fixed here https://github.com/poanetwork/metamask-extension/pull/165/commits/5ce9bb7d1cd7a086275a3ce81f91c6c6d1bbcdb7

**Pull request merged**
