### PR TITLE
(Fix) Sign data and recover account pages styles fixes

### PR DESCRIPTION
**Pull request by vbaranov**
Before:
screen shot 2018-10-30 at 17 43 00

After:
screen shot 2018-10-30 at 13 39 06

Also, `react-hyperscript` was rewritten with JSX for those pages.

The signing od data and recovering of account can be tested with https://danfinlay.github.io/js-eth-personal-sign-examples/

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@vbaranov 
If account balance is zero then  word None' is displayed instead zero 
screen shot 2018-10-30 at 5 09 57 pm

Similar https://github.com/poanetwork/metamask-extension/issues/155'

**Comment by vbaranov** [comment]
>If account balance is zero then word 'None' is displayed instead zero

@dennis00010011b component fixed here https://github.com/poanetwork/metamask-extension/pull/177

**Comment by dennis00010011b** [comment]
@vbaranov 
Screen 'Confirm transaction': incorrect background color  for title and footer

screen shot 2018-11-01 at 10 51 36 am

**Comment by vbaranov** [comment]
@dennis00010011b great catch! thanks. Fixed here https://github.com/poanetwork/metamask-extension/pull/174/commits/428b39d4af971f8ed81ea1b8bb49569ed5c6b439

**Pull request merged**
