### PR TITLE
(Feature) Unlimited amount of custom RPC endpoints

### PR DESCRIPTION
**Pull request by vbaranov**
Relates to https://github.com/poanetwork/metamask-extension/issues/26

Unlimited numbers of custom RPCs can be added.
Networks dropdown was updated to support vertical scroll.

### CODE REVIEW

**Comment by vbaranov** [comment]
@patitonar I was trying to visualize scrollbar before submitting a PR. And decided not to include visualization, because of some visual artefacts at dropdown opening/closing animation. I would suggest adding visualization in a separate PR.

**Comment by dennis00010011b** [comment]
@vbaranov 
If network is LOCALHOST then
Settings->Current RPC field is  empty  
screen shot 2018-08-31 at 8 30 47 am

or custom rpc name displayed if there is custom rpc has been added
screen shot 2018-08-31 at 8 31 30 am

**Comment by vbaranov** [comment]
@dennis00010011b 
>If network is LOCALHOST then
Settings->Current RPC field is empty

yes, it works in such way from the beginning. Could you please create a separate issue for that?

>or custom rpc name displayed if there is custom rpc has been added

I didn't catch this one. Could you clarify?

**Comment by vbaranov** [comment]
@fvictorio could you take a look to this PR? do you have any concerns?

**Comment by fvictorio** [comment]
Yes, sorry. This looks good. My only comment is that I think the new RPCs should be at the end of the list. Now the list shows the newest first (after `Localhost 8545`). But this is something that can be done in a separate PR.

**Comment by vbaranov** [comment]
>My only comment is that I think the new RPCs should be at the end of the list. Now the list shows the newest first (after Localhost 8545). But this is something that can be done in a separate PR.

It makes sense, especially for the big list of custom RPCs and while we have no ability to hide the list of custom RPCs. I added this fix to PR. Thank you.

**Pull request merged**
