### PR TITLE
(Feature) Add button to delete custom rpc

### LINKED ISSUE #17: Delete button for custom RPC
Custom RPC should have a `Delete` button to remove them from the list https://cl.ly/0E2O2E0E1m2f
When the button is pressed a popup should appear "Are you sure to delete %custom_rpc_name%" with Yes and No button.

Only Custom RPC can be deleted

### PR DESCRIPTION
**Pull request by patitonar**
Closes #17

### CODE REVIEW

**Comment by fvictorio** [comment]
I am having this problem: if I add a custom RPC and then I go to another network, the RPC that I added disappears. This seems to be happenning in `develop` too, but maybe it should be fixed in this PR.

@vbaranov is the same thing happening to you?

**Comment by vbaranov** [comment]
>I am having this problem: if I add a custom RPC and then I go to another network, the RPC that I added disappears. This seems to be happenning in develop too, but maybe it should be fixed in this PR.

@fvictorio interesting, I did not pay attention on this issue

**Comment by patitonar** [comment]
@vbaranov Added a scroll bar for long rpc url
scrolldeleterpc

**Comment by patitonar** [comment]
@fvictorio @vbaranov Fixed custom rpc not showing on the list after switching to another network

**Pull request merged**
