### PR TITLE
(Fix) change extension name and icons

### PR DESCRIPTION
**Pull request by vbaranov**
Relates to https://github.com/poanetwork/metamask-extension/issues/5
Relates to https://github.com/poanetwork/metamask-extension/issues/8

PR consists of:
- changing of icons
- changing of titles of the pages
- changing of the name of extension in the pages
- changing the name of the extension in log messages and alerts
- removing of links from Info page
- removing of "Try Beta!" button
- removing of "try beta version" link from the signup page

### CODE REVIEW

**Comment by vbaranov** [comment]
There are some screenshots:

screen shot 2018-07-17 at 20 36 51
screen shot 2018-07-17 at 20 36 39
screen shot 2018-07-17 at 20 36 15
screen shot 2018-07-17 at 20 35 50

**Comment by igorbarinov** [comment]
On info page
there is the Metamask name
https://cl.ly/00450K2P360K

also, let's remove all links https://cl.ly/0O1y3V22350A

**Comment by vbaranov** [comment]
@igorbarinov fixed
ALso, "Try beta!" button is removed

screen shot 2018-07-18 at 13 52 11
screen shot 2018-07-18 at 13 51 56

**Comment by patitonar** [comment]
On `Terms of Use` there are references to MetaMask name.
screenshot_20180718_120230

**Comment by vbaranov** [comment]
@patitonar I guess we should write terms of use for "Nifty wallet" from scratch or we should remove this screen form the signup step. @igorbarinov?

**Comment by patitonar** [comment]
besides the comment about terms of use, the rest looks good to me

**Comment by vbaranov** [comment]
>besides the comment about terms of use, the rest looks good to me

ok, let's consider it in a separate issue/PR. I'm gonna to merge.

**Pull request merged**
