### PR TITLE
(Feature) Add button to remove token

### LINKED ISSUE #23: Delete button for Token
Add delete button for Token near Add token
https://cl.ly/2F3e3E2t3k1n

when pressed a trashcan icon appears near each token. After pressing the trashcan icon a popup appears `Are you sure to delete %token%?`. After yes, the token is removed from the list and Delete mode becomes not enabled. If no, the token is not removed from the list and Delete mode becomes not enabled.

### PR DESCRIPTION
**Pull request by fvictorio**
Closes #23.

Add button to remove tokens. This doesn't have tests yet, see #30.

### CODE REVIEW

**Comment by vbaranov** [comment]
@fvictorio could you get upstream for this branch? It seems Git doesn't recognize a branch with "#" at the beginning.

**Comment by fvictorio** [comment]
@vbaranov Done.

**Comment by fvictorio** [comment]
From what I understand, the parent repo has two UIs: one beta ui (in the `ui` directory) and the old ui (in `old-ui`). The redux action to remove the token was already there, and I guess that option is implemented (or will be) in the new UI. I added the button and the confirmation screen.

**Comment by vbaranov** [comment]
Ah, ok. Makes sense.

**Pull request merged**
