### PR TITLE
(Upgrade) get upstream from MM 4.9.3

### PR DESCRIPTION
**Pull request by vbaranov**
get upstream from MM 4.9.3

@dennis00010011b please fix e2e and integration tests

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@vbaranov 
Token balance displayed only for account where it was added
Should be displayed for each account in network
Tested with localhost , Sokol 0x229483ce51cbe485c93496c5c19ebb422596acc8
screen shot 2018-10-18 at 10 30 57 pm

**Comment by vbaranov** [comment]
@dennis00010011b e2e tests for Firefox look unstable. Could we improve them?

**Comment by dennis00010011b** [comment]
@vbaranov 
There is issue for Firefox https://github.com/poanetwork/metamask-extension/issues/167
That's why e2e failed
I can skip this test for current PR

**Comment by vbaranov** [comment]
@dennis00010011b yes, let’s skip for this PR.

**Pull request merged**
